### ISSUE TITLE
A question about COCO results in your paper

### ISSUE THREAD

**Issue by peiyingxin** [DoctorKey/LSHFM.detection#1]
hi, thanks for your sharing ~
In your paper table 15, the result of resnet50 on COCO dataset mAP is up to 77.16,I was wondering how you calculated? Is it the official calculation method?
so far, SOTA of COCO detection is 63.3mAP,  How did you to improve to such a high level of precision?

**Comment by DoctorKey** [comment]
Results for multi-label classification are showed in Table 15. Note that it is not the object detection task. Please read section 5.3 for more details. For object detection, please read section 5.4. We use mAP@0.5 as the metric.
